[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tunesynctool"
version = "1.5.0"
authors = [
    { name="WilliamNT" },
    { name="FaintWhisper" }
]
description = "A package and CLI tool to build scripts that interact with various music streaming services."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Intended Audience :: Developers",
]
dependencies = [
    "spotipy",
    "spotifyscraper>=3.9.2,<4",
    "py-sonic",
    "musicbrainzngs",
    "thefuzz",
    "ytmusicapi",
    "click",
    "tqdm",
]

[project.optional-dependencies]
deezer = [
    "streamrip>=2.1,<3",
    "deezer-py>=1.3.6,<2",
]

[project.urls]
Homepage = "https://github.com/WilliamNT/tunesynctool"
Issues = "https://github.com/WilliamNT/tunesynctool/issues"
Documentation = "https://github.com/WilliamNT/tunesynctool/wiki"

[project.scripts]
tunesynctool = "tunesynctool.cli.main:cli"
